# Generated by Django 3.1.5 on 2021-01-23 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de actualizacion')),
            ],
            options={
                'verbose_name': 'Encuesta',
                'verbose_name_plural': 'Encuestas',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pregunta', models.TextField(verbose_name='Pregunta?')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de actualizacion')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.encuesta', verbose_name='encuesta')),
                ('pregunta_previa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previa', to='encuestas.pregunta', verbose_name='Pregunta previa')),
                ('pregunta_sgte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siguiente', to='encuestas.pregunta', verbose_name='Pregunta siguiente')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('respuesta', models.CharField(choices=[('DE_ACUERDO', 'De acuerdo'), ('EN_DESACUERDO', 'En desacuerdo'), ('NO_SABE', 'No sabe/no opina')], max_length=50, verbose_name='Respuesta')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Fecha y hora de actualizacion')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encuestas.pregunta', verbose_name='pregunta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
    ]
